class Cart_Page_Locators():
    cart_button = "//a[@id='cartur']"
    click_place_order_button = "//button[contains(text(),'Place Order')]"
    total_name = "//input[@id='name']"
    country_name = "//input[@id='country']"
    city_name = "//input[@id='city']"
    cridit_carde = "//input[@id='card']"
    month = "//input[@id='month']"
    year = "//input[@id='year']"
    purchase = "//button[contains(text(),'Purchase')]"
    close_button = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
    cart_button1 = "//a[@id='cartur']"
    click_place_order_button1 = "//button[contains(text(),'Place Order')]"
    path_name = "//input[@id='name']"
    name = "elsa"
    null = " "
    special_character = "@$#@#$%%^%%#"
    country_name1= "//input[@id='country']"
    Cuntry = "Ethiopia"
    city_name1 = "//input[@id='city']"
    City = "Gondar"
    cridit_carde1 = "//input[@id='card']"
    Card = "2346578"
    month1 = "//input[@id='month']"
    mo_nth = "6"
    x = "//body/div[@id='orderModal']/div[1]/div[1]/div[1]/button[1]/span[1]"
    year1 = "//input[@id='year']"
    ye_ar = "2000"
    purchase1 = "//button[contains(text(),'Purchase')]"
    close_button1 = "//body/div[@id='orderModal']/div[1]/div[1]/div[3]/button[1]"
