contact_link="//a[contains(text(),'Contact')]"
contact_email="//input[@id='recipient-email']"
contact_name="//input[@id='recipient-name']"
contact_message="//textarea[@id='message-text']"
send_message="//button[contains(text(),'Send message')]"
close="//body/div[@id='exampleModal']/div[1]/div[1]/div[3]/button[1]"
x_path="//body/div[@id='exampleModal']/div[1]/div[1]/div[1]/button[1]/span[1]"
contact_send_message = "//button[contains(text(),'Send message')]"
close_send_message = "//body/div[@id='exampleModal']/div[1]/div[1]/div[3]/button[1]"
x_button = "//body/div[@id='exampleModal']/div[1]/div[1]/div[1]/button[1]/span[1]"
