class Test_login():
    login1="//a[@id='login2']"
    loguser="//input[@id='loginusername']"
    logpass="//input[@id='loginpassword']"
    logbutton="//button[contains(text(),'Log in')]"
    logclose="//body/div[@id='logInModal']/div[1]/div[1]/div[3]/button[1]"
    logx="//body/div[@id='logInModal']/div[1]/div[1]/div[1]/button[1]/span[1]"
    login_button = "//a[@id='login2']"
    correct_user_name = "//input[@id='loginusername']"
    correct_passward = "//input[@id='loginpassword']"
    login = "//button[contains(text(),'Log in')]"
    close_button = "//body/div[@id='logInModal']/div[1]/div[1]/div[3]/button[1]"
    x_path_button = "//body/div[@id='logInModal']/div[1]/div[1]/div[1]/button[1]/span[1]"
